baseURL: https://notes.improvisedscience.org/
languageCode: en-us
title: notes.improvisedscience.org.
theme: papermod
env: production
outputs:
  home:
    - HTML
    - RSS
    - JSON
taxonomies:
  category: categories
  tag: tags
  method: methods
  theme: themes
params:
  description: "Recipes!"
  ShowToc: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: methods
      name: methods
      url: /methods/
      weight: 40
    - identifier: themes
      name: themes
      url: /themes/
      weight: 50
