name = "notes-improvisedscience-org"

[build]
command = "hugo -b https://notes.improvisedscience.org/"
cwd = ""

[build.environment_variables]
HUGO_VERSION = "0.148.1"

[env.production]
[env.production.build]
command = "hugo -b https://notes.improvisedscience.org/"

[env.preview]
[env.preview.build]
command = "hugo -b $CF_PAGES_URL"