name = "notes-improvisedscience-org"

# Pages configuration
pages_build_output_dir = "public"

[build]
command = "hugo --minify -b https://notes.improvisedscience.org/"

[build.environment_variables]
HUGO_VERSION = "0.148.1"

[env.production]
[env.production.build]
command = "hugo --minify -b https://notes.improvisedscience.org/"

[env.preview]
[env.preview.build]
command = "hugo --minify -b $CF_PAGES_URL"