name = "notes-improvisedscience-org"

# Pages configuration
pages_build_output_dir = "public"

[env.production]
command = "hugo --minify -b https://notes.improvisedscience.org/"

[env.production.env_vars]
HUGO_VERSION = "0.148.1"

[env.preview]
command = "hugo --minify -b $CF_PAGES_URL"

[env.preview.env_vars]
HUGO_VERSION = "0.148.1"